# Generated by Django 5.0.2 on 2024-02-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_professionalexperience_relevance_project_relevance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='college',
            name='degree',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='college',
            name='end_date',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='college',
            name='start_date',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='organization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
