# Generated by Django 5.0.2 on 2024-02-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_college_cgpa_alter_resume_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='end_date',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='start_date',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
